default: &default
    adapter: mysql2
    encoding: utf8
    database: <%= Settings.databaseName %>
    pool: 10
    username: <%= Settings.databaseUsername %>
    password: <%= Settings.databasePassword %>
    host: <%= Settings.databaseHost %>

development:
    <<: *default

test:
    <<: *default
    database: <%= Settings.databaseTestName %>

staging:
    <<: *default

production:
    <<: *default
