default: &default
    secret_key_base: <%= Settings.secretKeyBase %>
    secret_token: <%= Settings.secretToken %>

development:
    <<: *default

test:
    <<: *default

staging:
    <<: *default

production:
    <<: *default